### ISSUE TITLE
Can't plan a trip if user doesn't select values from Start/End drop down lists

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#49] opened 2015-08-12 19:27 UTC
When the user is planning a trip, if they enter text into the Start/End boxes, but don't select a value from the drop-down list, the trip plan fails:

![image](https://cloud.githubusercontent.com/assets/928045/9234363/7506dc74-4106-11e5-858b-d07b15f8aa5c.png)

If the building abbreviations haven't been geocoded when the user selects "Plan Your Trip", we should geocode at that time so the trip plan succeeds.

**Comment by jailby** [comment] 2015-08-14 13:41
Also, if a trip was already plan before this bug no error message will appear and the only thing returned will be the old trip.

**Comment by jmfield2** [comment] 2015-08-29 18:41
To clarify, I think the "no error message" occurs when you plan a route as in below:

![image](https://cloud.githubusercontent.com/assets/3628509/9563692/98f73a46-4e5a-11e5-9256-e704f09afb8d.png)

And then go back to change the start or end, but don't select the result correctly resulting in something like:

![image](https://cloud.githubusercontent.com/assets/3628509/9563695/a511f74e-4e5a-11e5-930d-6893a4cac4a1.png)

I believe I have fixed both cases, and will submit a PR shortly.

**Comment by barbeau** [comment] 2015-08-29 21:43
I've seen this upon initial page load too, and just replicated on mobile in
Chrome (see screenshot).  The only way you can plan a trip is if the
geocode completes prior to hitting the plan trip button.

Upon load, try typing CUT into origin, than tap on destination field
without selecting from drop down or tabbing, type MSC, and then click on
trip plan before selecting anything from drop down.  It's easier to
replicate on mobile because the geocode takes longer to complete,
especially on 3g connection, and you can't tab.

**Comment by jmfield2** [comment] 2015-08-29 22:08
Hm.  Thanks for that - I originally didn't try on mobile but you're right that makes reproducing that part of the issue much easier to see.   

Since the autocomplete will stop onblur (I'm pretty sure) and no results will be available, that part of the  issue wouldn't be fixed by my proposal - so I guess the best way is to (like you said) geocode the start/end again when plan a trip is clicked and verify that the start/end markers match -- fixing them if necessary.  

If no results are found, the current "please select a start/end" behavior seems appropriate, right?

If more than one result is found, ideally we would ask or notify the user - but perhaps selecting the first is OK for now?

**Comment by barbeau** [comment] 2015-08-29 23:14
IMHO, yes to both.  That would be a big improvement over current behavior.
We can open another ticket for enhancement to ask user if more than one
result that's a lesser priority.
On Aug 29, 2015 6:08 PM, "jmfield2" notifications@github.com wrote:

Hm. Thanks for that - I originally didn't try on mobile but you're right
that makes reproducing that part of the issue much easier to see.

Since the autocomplete will stop onblur (I'm pretty sure) and no results
will be available, that part of the issue wouldn't be fixed by my proposal
- so I guess the best way is to (like you said) geocode the start/end again
  when plan a trip is clicked and verify that the start/end markers match --
  fixing them if necessary.

If no results are found, the current "please select a start/end" behavior
seems appropriate, right?

If more than one result is found, ideally we would ask or notify the user -
but perhaps selecting the first is OK for now?

**Closed as completed** 2015-11-13 02:21 UTC
Labels: bug
