### ISSUE TITLE
Map centers on downtown Tampa when using hard-wired USF PC and Chrome/Firefox

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#5] opened 2014-08-05 13:45 UTC
For real-time location in MoBullity, we’re using Leaflet for the web app, and its locate() method:
http://leafletjs.com/reference.html#map-locate

This in turns uses the W3C Geolocation API:
https://en.wikipedia.org/wiki/W3C_Geolocation_API

If you visit the site from a wired USF PC (e.g., hardwired here at CUTR, or in ENB, and I suspect other locations at USF) in Chrome or Firefox, the browser geolocation resolves to downtown Tampa:

![image](https://cloud.githubusercontent.com/assets/928045/3811989/7754aece-1ca5-11e4-81c5-19c24b55a2f0.png)

Since MoBullity is primarily useful for the USF Tampa campus, to fix this we should automatically center the map on the USF Tampa campus if we detect that the user's real-time locationi is outside the USF Tampa campus area (bounding box a little larger than USF Tampa).

Also noteworthy - if you use IE, it seems to resolve inside USF but near the center of campus (which is fine).  If you visit the site from a laptop w/ wireless connection, it seems to locate you correctly for all browsers.

**Comment by jmfield2** [comment] 2014-08-07 02:37
I think this patch will fix this. 

```
------------------------- src/client/js/otp/config.js -------------------------
index eec50e7..eeaecaa 100644
@@ -54,6 +54,7 @@ otp.config = {
     geoLocation: true,
     //if user does not allow location finding default location set
     initLatLng : new L.LatLng(28.058499, -82.416945), 
+   usfLatLngBoundary: new Array( new L.LatLng(28.080556, -82.451454), new L.LatLng(28.032913, -82.373949) ), /* Top-Left, Bottom-Right */
     initZoom : 14,
     minZoom : 8,
     maxZoom : 20,

------------------------ src/client/js/otp/core/Map.js ------------------------
index 4c6abc3..c88714a 100644
@@ -77,7 +77,17 @@ otp.core.Map = otp.Class({
             };

             /* sets a marker at the current location */
-            function onLocationFound(e){               
+            function onLocationFound(e){
+
+       // Ensure latlng is within bounding box, else clamp to default point
+       if (e.latlng.lat > otp.config.usfLatLngBoundary[0].lat || e.latlng.lat < otp.config.usfLatLngBoundary[1].lat ||
+           e.latlng.lng < otp.config.usfLatLngBoundary[0].lng || e.latlng.lng > otp.config.usfLatLngBoundary[1].lng) {
+           pos = otp.config.initLatLng;
+           /* Should we change e.accuracy since we changed the location? @TODO */
+           console.log("LatLng clamped to USF");
+       }
+       else pos = e.latlng;
+
                var locationSpot = L.Icon.extend({
                    options: {
                        iconUrl: resourcePath + 'images/locationSpot.svg',
@@ -88,13 +98,13 @@ otp.core.Map = otp.Class({
                tempM = marker;
                tempA = accCircle;
                var locSpot = new locationSpot();
-               marker = L.marker(e.latlng,{icon : locSpot,}).bindPopup('Current Location');
-               accCircle = L.circle(e.latlng,e.accuracy,{color:"blue", opacity: .25, fillOpacity: .1, weight: 3});
+               marker = L.marker(pos,{icon : locSpot,}).bindPopup('Current Location');
+               accCircle = L.circle(pos,e.accuracy,{color:"blue", opacity: .25, fillOpacity: .1, weight: 3});
                //adds new marker and accuracy circle
                this.addLayer(marker);
                this.addLayer(accCircle);
                //if statement will make it so the map only zooms on the first function call
-               if (count == 1){this.setView(e.latlng, 17);};
+               if (count == 1){this.setView(pos, 17);};
                //following removes the last set of map markers on the last function call
                this.removeLayer(tempM);
                this.removeLayer(tempA);
```

**Comment by barbeau** [comment] 2014-08-07 02:55
Thanks @jmfield2!  Could you put this and the other patch into pull
requests?  Its makes it easier to review and comment on specific lines.

**Comment by TNWolf** [comment] 2014-08-07 17:00
I applied this patch. However now it appears to always show the location as
the default location instead of my current location even when I have
location services allowed.

**Comment by jmfield2** [comment] 2014-08-07 17:18
Hmm .. Maybe I flipped a sign in one of the boundary checks or a precision
issue.. Can you try to log your position e.latlng in the on location
changed before it defaults?

**Comment by TNWolf** [comment] 2014-08-07 17:50
Actually just realized, are the bounds set for USF?

I'm not on campus so I guess I would be outside the bounds so it would
resort to the default location.. If that's the case this fix might be an
issue for people planning a trip from their apt/house to campus.

**Comment by jmfield2** [comment] 2014-08-07 17:53
They are set for USF so that's the probably why.. Good idea re: people
planning trips to campus...

**Comment by barbeau** [comment] 2014-08-07 18:34
Maybe a better way to handle this issue is to check if the real-time location is equal to the erroneous default "downtown" location, then recenter on USF.  This wouldn't interfere with people planning trips from off-campus locations to USF.

**Comment by barbeau** [comment] 2014-08-07 18:38
Here's another screenshot of the erroneous default downtown location, zoomed in closer and without the warning box:
![image](https://cloud.githubusercontent.com/assets/928045/3847026/de7e6122-1e61-11e4-80e7-17a9048b017a.png)

I don't have mobullity app set up on my machine to debug, but if there is another way to grab the exact lat/long from the browser let me know.

**Comment by jmfield2** [comment] 2014-08-08 12:14
I noticed that I have the same issue on my desktop @ home -- but instead of Tampa, it is centered on Clearwater.  I think this is happening because navigator.geolocation can't get an accurate location (especially non-wifi) and finds the closest city center instead.  The location object returns an accuracy of 22,000 meters to represent this in my testing. 

So, we can check for e.accuracy, and then perhaps reset the zoom level to encompass more of the area just in case some off-campus students are on wired connections too? ... It will still break for any students trying to route from outside of Tampa, though... I'm not sure how effective that would be anyway ... unless they only need driving directions.

**Comment by barbeau** [comment] 2014-08-08 13:29
@jmfield2 Agreed, it seems that navigator.geolocation on Firefox and Chome can't provide decent accuracy on wired connections.

The check for accuracy is probably a good solution - always center on USF campus if the accuracy is above a certain threshold.  This zoom level is probably ideal for a default:

![image](https://cloud.githubusercontent.com/assets/928045/3857031/405b60aa-1eff-11e4-8670-db5c6bbf6d77.png)

We should also center on USF if the user's real-time location is outside the greater Tampa Bay area (something close to the below bounding box), since we'll only provide routing for Bull Runner/HART/PSTA coverage area:

![image](https://cloud.githubusercontent.com/assets/928045/3857099/e51c7930-1eff-11e4-92bb-9e8a1efee448.png)

So, centering on the user's location outside of this area doesn't do the user much good since we won't have data for their area.  Plus, if a user visits this site from far away (e.g., Seattle), they are likely interested in seeing how to get around the campus, not on how to get to the campus.

**Comment by luqmaan** [comment] 2014-08-12 16:10
Just in case you don't already know this (I don't see it in the code), try setting `enableHighAccuracy` to `true`. http://leafletjs.com/reference.html#map-locate-options.

Having a fallback location is a good idea too, tho.

**Comment by barbeau** [comment] 2014-08-12 17:20
Thanks @luqmaan, that's definitely a good suggestion.  I know we had talked about this previously, and I believe that is already set somewhere.

@TNWolf Could you please take another look and make sure `enableHighAccuracy` is set to `true`?

**Comment by TNWolf** [comment] 2014-08-15 17:01
I think the merge on the recent fix has effected the initial zoom level. When I load the map it's all the way zoomed out. I believe it was previously set to the zoom level that had the map showing the name of the buildings around them, since the names of the buildings don't show up unless someone is zoomed in enough.

**Comment by jmfield2** [comment] 2014-08-19 15:18
In working on tracking down the regression caused by this fix, I discovered a couple of things. 

The simple fix is to change:
https://github.com/jmfield2/usf-mobullity/blob/c1003ed71e0ccf19a465116ffdf2a9b90323d053/src/client/js/otp/core/Map.js#L128

15 (back) to 17 here, the regression should be fixed... but it doesn't seem to always work for me.

So, I dug a little more and I think it's a race condition-like issue in our version of leaflet (0.5.1 vs the latest stable 0.7.3) and described in https://github.com/Leaflet/Leaflet/issues/2521

Since it's probably going to be a task to upgrade leaflet, a simple-ish workaround is to check that _animateToZoom actually worked and if not, reset 'count' so the zoom code in onLocationFound(e) will be executed again.

Any other thoughts?

**Comment by barbeau** [comment] 2014-08-19 17:21
@jmfield2 Has the Leaflet interface changed substantially from 0.5.1 to 0.7.3?  It would be nice if we could bring our Leaflet client to up date, since I'm sure there are other issues lurking in the old version.

**Comment by jmfield2** [comment] 2014-08-19 17:27
I tried to manually patch the issue described from their Github and really
didn't get too far ... So I think it has changed a fair amount but I can
check on it more .. Maybe create a new local branch and issue for upgrading?

**Comment by barbeau** [comment] 2014-08-19 17:40
@jmfield2 Sounds good to me.  If it ends up being a deep rabbit hole we can just looking at patching it with a workaround.

**Comment by TNWolf** [comment] 2014-10-15 16:22
I just ran this test again on my laptop with wifi disabled. Currently on campus in the ENB building using a hard wired connection and got a result of zoomed out Tampa and no current location icon was set. The output to the console was "Accuracy beyond threshold; recentering on USF. " which is correct.

I will start looking into this some more.

![screenshot 2014-10-15 12 19 23](https://cloud.githubusercontent.com/assets/5204472/4649068/59c8f83c-5487-11e4-9b33-eaa909244edf.png)

**Comment by TNWolf** [comment] 2014-10-16 16:38
Everything appears to be working fine on wired connection. Closing issue.

**Closed as completed by TNWolf** 2014-10-16 16:38 UTC
Labels: bug
