### ISSUE TITLE
Context menu don't stay open on Firefox

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#192] opened 2016-02-19 15:49 UTC
I recently noticed a bug that I was able to reproduce only on Firefox (I tried Firefox and Chrome).

Problem:
When right-clicking on the map the context menu opens but only for the time the right click is hold. Once the mouse button is released the context menu disappear.

I believe that the menu should persist. When a user right click on the map the context menu should open and only disappear if the user select one of the entry or click elsewhere on the map. 

To reproduce the bug open maps.usf.edu on Firefox and try right-clicking on the map. I had 80% reproduction rate.

**Comment by barbeau** [comment] 2016-02-19 16:06
@jailby I can't reproduce this on Firefox 44.0.2 on Windows 7 Enterprise - right-clicking always opens the context menu.  What platform and version of Linux/Firefox are you using?

**Comment by cagryInside** [comment] 2016-02-19 16:46
I tested with my computer and reproduce the problem:
Firefox version 44.0.2, Mac OS X El Capitan 10.11.3

**Comment by jailby** [comment] 2016-02-19 16:49
Firefox version 41.0.1, Linux Mint 17.1

**Comment by barbeau** [comment] 2016-02-19 22:09
Possibly a related issue on IE 11.0.9600.18204 on Windows 7 Enterprise and Pro.

If you open the context menu it always responds and opens (i.e., same behavior as Chome), but it looks like this:

![image](https://cloud.githubusercontent.com/assets/928045/13190481/52adcf0a-d72b-11e5-9550-5763e5626441.png)

**Comment by jmfield2** [comment] 2016-02-25 14:21
I believe the context menu hiding issue is the result of the way firefox handles the event vs other browsers - there are two at work, one for the contextmenu event, and another global click event that is used to hide the menu whenever the mouse is clicked later.  Both events are triggered on click, resulting in the menu immediately hiding on FF.

RE: js/otp/core/ContextMenu.js, and PopupMenu.js

There is a config option to 'suppress hide' but I don't think this is what we want.  I thought simply fixing the missing "event.preventDefault()" with event.originalEvent.preventDefault() would fix the issue, but it does not seem to have an effect.

Instead, we can add a flag to the contextmenu handler so that the click handler will ignore the next click event instead of hiding the menu.. This seems to mostly work, but sometimes it does seem to ignore legitimate clicks that I would expect to hide the menu..  It could be an improvement while looking into a better solution, though.

I haven't checked into the layout issues shown with IE11

**Closed as completed** 2016-03-07 20:53 UTC
Labels: bug
